### ISSUE TITLE
Update download location to GitHub

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa-ansible#1]
Old download on sympa.org is not up-to-date as discussed on IRC - newer releases are missing there.

**Comment by dverdin** [comment]
One: We need to keep the previous download URL working. I'll see what I can do about it.
Second: as discussed in the chat, we need to allow install from the git (most recent master for example). We will need it for our playground server.

**Comment by racke** [comment]
We got 6.2.22 on the old download, but no older 6.2.x releases right now.

**Comment by dverdin** [comment]
All releases are now available at https://www.sympa.org/distribution/releases/.
All releases are named this way : sympa-<version>.tar.gz
They are all accompanied by sha-256 and MD5 sum files named respectively:
- sympa-<version>.tar.gz.sha256
- sympa-<version>.tar.gz.md5
