### ISSUE TITLE
Sympa upgrades are not supported

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa-ansible#2]
Nov  8 16:31:42 local-sympa-ubuntu16 wwsympa[15808]: err main::#997 > Conf::data_structure_uptodate#741 Data structure (6.2.16) is not uptodate for current release (6.2.22)
Nov  8 16:31:42 local-sympa-ubuntu16 wwsympa[15808]: err main::#999 WWSympa set to maintenance mode; you should run sympa.pl --upgrade

**Comment by dverdin** [comment]
OK. Actually, we could run sympa.pl --upgrade systematically. If no upgrade is required, it simply exits.

**Comment by racke** [comment]
Correct, I already tried that. Not trivial, as it needs to be run as sympa user. We probably need a wrapper script to make this possible.

**Comment by dverdin** [comment]
Now the upagrade is executed - at the right time - during the deployment process.
