### ISSUE TITLE
Split sympa-ansible in multiple repositories

### ISSUE THREAD

**Issue by Scriptkiddi** [sympa-community/sympa-ansible#28]
Shouldn't there be more repositories that install a sympa server? And not the complete ansible inventory?
I was wondering if there would be the possibility to split this repository into multiple repositories to allow further development and reusage for small parts.
I would be interested to extend the sympa role, but not with apache and since we use our own common role, I would think I would be a great help putting the sympa role into its own repository and listing the dependencies or the requirements for this role to work.
What do you guys think?

**Comment by dverdin** [comment]
Yep, I'm finishing a refactoring of the plyabook into which Apache and Postfix specific tasks are isolated.
That way, it should be easier to use either Apache or another web server (the same applies for Postfix).
More news shortly.

**Comment by Scriptkiddi** [comment]
Do you have a branch where you working on I would be happy to help

**Comment by dverdin** [comment]
Actually, It's on a separate, private repository for now. This is because my work is part of a larger system and I needed to ensure said system worked prior to considering factorizations an reversion to the Sympa project.
I'll post the result here as soon as possible.

**Comment by racke** [comment]
I think that is unfortunate, as you miss valuable input and we probably have to cope with a large PR to incorporate into this repository. 

BTW: Did you ever consider to use external roles from Ansible Galaxy for webserver/mail server configuration?

**Comment by dverdin** [comment]
Yes but, as I said, my work is part of a larger system. Not only Sympa, then. And I don't want to share some half-done work.
Indeed, that will be a big PR but remember we have Travis on this project.
And, yes, I'm interested in Galaxy, of course. Actually, the work towards this has started as we have now roles dedicated to Postfix and Apache.

**Comment by dverdin** [comment]
As I am about to send a PR: Does anybody have any pointer about ho to work with mutiple repositories in one directory? The reason I send one big PR is that we had to work on Universalistes revamping. This service uses Sympa and other tools to provide groupware funtionnalities. To deply, we had a big ansible project of which Sympa was a part. So while building the Universalistes playbook, we improved Sympa playbook. But all this work was done decorrelated from the github repository. So I sent my change back to the sympâ-ansible community project by making an rsync, then committing. Therefore it is impossible to have a look at the full commit history.
As Racke said, it is unfortunate.
But I honestly don't see ow to do it, apart from making regular rsync.
Any other solution?

**Comment by Scriptkiddi** [comment]
Hey take a look at submodules  they let you add another git repository inside your other git repository 
Oh and if there should be a dependency between roles one can use ansible galaxy to define it without the need of everything being in on project

**Comment by ikedas** [comment]
@dverdin, are you talking about sympa and historic-sympa repositories?

**Comment by dverdin** [comment]
@Ikedas : I am talking about the sympa-ansible project. So none of these. Only the sympa installation through Ansible.

**Comment by dverdin** [comment]
@Scriptkiddi : Thanks, I'll look at submodules. @racke suggested Galaxy, too. I'll definitley look at this in details.
I failed to make my PR yesterday, due to... let's say "external contingencies" ;-)
I'll retry it next week.

**Comment by racke** [comment]
I like git subtree better, because it prevents dependency on another repository. 

Also you can use git filter-branch to extract commits which only contain the files you specify.
E.g. https://wiki.linuxia.de/library/stefan-hornburg-racke-git-cheatsheet-en#text-amuse-label-gitbreakoutnewrepo

**Comment by ikedas** [comment]
> @ikedas : I am talking about the sympa-ansible project. So none of these. Only the sympa installation through Ansible.

I see. I think you may use submodule.

**Comment by dverdin** [comment]
Thanks to all for your advices.
I'll do my best to put them in use in my day to day work, so that anything related to Sympa can be easily and clearly snet back here.
Cheers!
David

**Comment by dverdin** [comment]
Hi @Scriptkiddi !
We made a big refactoring on the playbok and just published it.
I can't directly request review from you because you did not request "Sympa community" membership, but if you want to have a look, you can see that, though it is not perfect yet, we tried to remove a lot of things from the sympa role.
That's a first step towards splitting the Sympa playbook into multiple repositories.
All details here: #37 !

**Comment by dverdin** [comment]
OK. Now that we merged the huge PR, the aims should be to:
- restrict the playbook to what is strictly necessary, relying the more possible on galaxy,
- allow to chose several external tools: exim, nginx, etc. by supporting multiple configurations.

**Comment by racke** [comment]
See also #46.

**Comment by racke** [comment]
Repository is obsolete.
