### ISSUE TITLE
Break out roles

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa-ansible#46]
Currently we have basically a big Sympa role that installs database, postfix, apache and sympa. Each one of these should become its own role. Also they should be executed in a more logical order:

1. database
2. sympa
3. postfix
4. apache

That would allow more flexibility as well, e.g. leaving out roles or replace with a different server (nginx, exim).

**Comment by Scriptkiddi** [comment]
We should agree on how we want to handle the other roles, do we only install sympa as is and only give recommendations for the other configurations so that everybody can choose their own roles to supplement the sympa role or do we pick roles that we support and set the values for them?
What do you guys think?

**Comment by dverdin** [comment]
All of the above. We can have a Sympa role that would be "as is" and the playbook, in which we would endorse some tools.

**Comment by Scriptkiddi** [comment]
so we split it into two repos one for the role and one for the playbook?

**Comment by dverdin** [comment]
I think that would be the idea. I'd like to make a Galaxy role for Sympa.
However, we need to work on the playbook as it is before being able to perform such a split.

**Comment by Scriptkiddi** [comment]
i already wrote a sympa role for debian, that only takes care of the sympa installation, i could check if i can merge it with your sympa tasks to make a role that should work on every system

**Comment by racke** [comment]
@Scriptkiddi - we are working on a roadmap that will include role split up. Can we see that Sympa role of yours?

**Comment by racke** [comment]
Repository is obsolete.
