### ISSUE TITLE
Use Systemd service + sockets instead of spawn-fcgi

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa-ansible#58]
This setup is described here:

https://nileshgr.com/2016/07/09/systemd-fastcgi-multiple-processes

**Comment by ikedas** [comment]
What is advantage of this method?

**Comment by racke** [comment]
Better integration with systemd + no need for spawn-fcgi.

**Comment by dverdin** [comment]
Reading the doc, it has another a large advantage: it looks like spawn-fcgi would not have a relaunch system. so if one out of five processes die, you keep having 4 processes running until you manually relaunch. Potentially, all processes could die and you would lose access to the web interface.
However, there is cookbook for nginx, but no indication for Apache. So it would require experimentation to prove it works with it.

**Comment by ikedas** [comment]
Also with spawn-fcgi, it will be relaunched, thanks to Restart=always directive in unit file.
This behavior is necessary, because wwsympa.fcgi can terminate itself when it is updated.

Anyway, if removal of spawn-fcgi will be harmless, it sounds good for me.

**Comment by dverdin** [comment]
OK. So we'll take care with the doc Racke linked, as it contains false informations.
Like I said: carefully.

**Comment by racke** [comment]
@dverdin can you please elaborate on the "false informations"?

**Comment by dverdin** [comment]
Oh, the point where it said: "there’s no re-launching mechanism if the processes die"; There is. So it's a false information.
Don't get me wrong: I did not say anything like "lies" or such. Nothing paranoid.
I just point that if it contained an error, it could contain other.

**Comment by dverdin** [comment]
I think that switching to this configuration could be a good place to start testing several web servers.

**Comment by racke** [comment]
Repository is obsolete.
